# https://github.com/ethpandaops/ethereum-package/blob/main/network_params.yaml
network:
  participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.15.10
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.0.0
    validator_count: 32
    count: 2

  additional_services:
    - dora # Helps to see validators are working
    - prometheus_grafana
    - blockscout

  mev_params:
    mev_relay_image: flashbots/mev-boost-relay
    mev_builder_image: ethpandaops/flashbots-builder:main
    mev_builder_cl_image: sigp/lighthouse:v7.0.0
    mev_boost_image: flashbots/mev-boost
    mev_boost_args: []
    mev_relay_api_extra_args: []
    mev_relay_housekeeper_extra_args: []
    mev_relay_website_extra_args: []
    mev_builder_extra_args: []
    mev_builder_prometheus_config:
      scrape_interval: 15s
      labels: {}
    mev_flood_image: flashbots/mev-flood
    mev_flood_extra_args: []
    mev_flood_seconds_per_bundle: 15
    custom_flood_params:
      interval_between_transactions: 1

  network_params:
    # this is 'kurtosis' network ID, which is a default network. With this configuration CL /spec endpoint will return CONFIG_NAME=testnet
    network_id: "3151908"
    deneb_fork_epoch: 0
    electra_fork_epoch: 0
    fulu_fork_epoch: 100000000
    
    # 74 = 32 validators * 2(number of el/cl nodes) + 10 (running on SSV/Anchor nodes) + 20 unregsitered validators
    # aligns with validator_count configuration under participants section
    preregistered_validator_count: 104
    seconds_per_slot: 12
    max_per_epoch_activation_churn_limit: 8
    # NOTE: changes the number of slots in the epoch and potentially some other network settings.
    # docs: https://github.com/ethpandaops/ethereum-package/blob/main/README.md#configuration
    # preset: minimal

monitor:
  enabled: true

nodes:
  ssv:
    count: 4
  anchor:
    count: 0
  
extra_params: 
  unregistered_validator_count: 20