# https://github.com/ethpandaops/ethereum-package/blob/main/network_params.yaml
network:
  participants:
  - el_type: geth
    el_image: ethereum/client-go:v1.15.10
    cl_type: lighthouse
    cl_image: sigp/lighthouse:v7.0.0
    validator_count: 32
    count: 2

  additional_services:
    - dora # Helps to see validators are working

  network_params:
    # this is 'kurtosis' network ID, which is a default network. With this configuration CL /spec endpoint will return CONFIG_NAME=testnet
    network_id: "3151908"
    deneb_fork_epoch: 0
    electra_fork_epoch: 0
    fulu_fork_epoch: 100000000
    
    # 74 = 32 validators * 2(number of el/cl nodes) + 10 (running on SSV/Anchor nodes) + 10 (unregistered validators)
    # aligns with validator_count configuration under participants section
    preregistered_validator_count: 84
    # NOTE: changes the number of slots in the epoch and potentially some other network settings.
    # docs: https://github.com/ethpandaops/ethereum-package/blob/main/README.md#configuration
    # preset: minimal

monitor:
  enabled: false

nodes:
  ssv:
    count: 4
  anchor:
    count: 0
  
extra_params: 
  unregistered_validator_count: 10
  